BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-gst"
BBFILE_PATTERN_qti-gst := "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-gst = "17"
LAYERDEPENDS_qti-gst = "qti-bsp"
LAYERSERIES_COMPAT_qti-gst = "kirkstone"

# do not error out on bbappends for missing recipes
BB_DANGLINGAPPENDS_WARNONLY = "true"
