BBFILES += "${LAYERDIR}/recipes/gstreamer/*.bb ${LAYERDIR}/recipes/packagegroups/*.bb ${LAYERDIR}/recipes/gstreamer/*.bbappend"
# 8550LU: qim-sdk.bb, others: tensorflow
BBFILES += "${@bb.utils.contains('BASEMACHINE', 'kalama', bb.utils.contains('PRODUCT', 'ubuntu', '${LAYERDIR}/recipes/qim-sdk/*.bb', '${LAYERDIR}/recipes/tensorflow/*.bb', d), '${LAYERDIR}/recipes/tensorflow/*.bb', d)}"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-gst"
BBFILE_PATTERN_qti-gst := "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-gst = "17"
LAYERSERIES_COMPAT_qti-gst = "dunfell kirkstone"

# do not error out on bbappends for missing recipes
BB_DANGLINGAPPENDS_WARNONLY = "true"