BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "qti-gst"
BBFILE_PATTERN_qti-gst := "^${LAYERDIR}/"
BBFILE_PRIORITY_qti-gst = "17"
LAYERSERIES_COMPAT_qti-gst = "kirkstone"

# do not error out on bbappends for missing recipes
BB_DANGLINGAPPENDS_WARNONLY = "true"

# add packagegroup-qcom-gst to the base image
CORE_IMAGE_EXTRA_INSTALL += "packagegroup-qcom-gst"

# remove packagegroup-qcom-gst from the base image for qcs9100
CORE_IMAGE_EXTRA_INSTALL:remove:qcs9100 = "packagegroup-qcom-gst"

# add packagegroup-qcom-gst-basic to the base image for qcs9100
CORE_IMAGE_EXTRA_INSTALL:qcs9100 += "packagegroup-qcom-gst-basic"

