inherit cmake pkgconfig

SUMMARY = "QTI open-source GStreamer Plug-in for qmmf-sdk"
HOMEPAGE = "http://www.qualcomm.com"
SECTION = "multimedia"

LICENSE = "BSD-3-Clause-Clear"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta-qti-bsp/files/common-licenses/${LICENSE};md5=3771d4920bd6cdb8cbdf1e8344489ee0"

# Dependencies.
DEPENDS := "gstreamer1.0"
DEPENDS += "gstreamer1.0-plugins-base"
DEPENDS += "gstreamer1.0-plugins-qti-oss-base"
DEPENDS += "qmmf-sdk"

FILESPATH =+ "${WORKSPACE}/vendor/qcom/opensource/gst-plugins-qti-oss/:"
SRC_URI = "file://gst-plugin-qmmfsrc/"
S = "${WORKDIR}/gst-plugin-qmmfsrc/"

# Install directries.
INSTALL_BINDIR := "${bindir}"
INSTALL_LIBDIR := "${libdir}"

# Default platform definitions.
IMAGE_MAX_WIDTH               := "4096"
IMAGE_MAX_HEIGHT              := "4096"
VIDEO_MAX_WIDTH               := "4096"
VIDEO_MAX_HEIGHT              := "4096"
VIDEO_MAX_FPS                 := "120/1"
CAMERA_METADATA_VERSION       := "1.0"
MULTI_CAMERA_ENABLE           := "FALSE"
GET_CAMERA_STATIC_INFO_ENABLE := "TRUE"

# Overwrite the default platform definitions for 8009.
VIDEO_MAX_WIDTH_apq8009   := "1920"
VIDEO_MAX_HEIGHT_apq8009  := "1080"
VIDEO_MAX_FPS_apq8009     := "30/1"

# Overwrite the default platform definitions for qrb5165.
IMAGE_MAX_WIDTH_qrb5165          := "9248"
IMAGE_MAX_HEIGHT_qrb5165         := "6944"
VIDEO_MAX_WIDTH_qrb5165          := "9248"
VIDEO_MAX_HEIGHT_qrb5165         := "6944"
VIDEO_MAX_FPS_qrb5165            := "480/1"
CAMERA_METADATA_VERSION_qrb5165  := "1.1"
VIDEO_UYVY_FORMAT_ENABLE_qrb5165 := "TRUE"
IMAGE_NV12_FORMAT_ENABLE_qrb5165 := "TRUE"

# Overwrite the default platform definitions for qrbx210.
CAMERA_METADATA_VERSION_qrbx210 := "1.1"
MULTI_CAMERA_ENABLE_qrbx210     := "TRUE"

# Overwrite the default platform definitions for qcs6490.
CAMERA_METADATA_VERSION_qcs6490 := "1.1"
VIDEO_MAX_FPS_qcs6490           := "240/1"

# Overwrite the default platform definitions for sdmsteppe.
VIDEO_YUY2_FORMAT_ENABLE_sdmsteppe        := "TRUE"
GET_CAMERA_STATIC_INFO_ENABLE_sdmsteppe   := "FALSE"
VIDEO_YUY2_FORMAT_ENABLE_qcs6490          := "TRUE"

EXTRA_OECMAKE += "-DGST_VERSION_REQUIRED=1.14.4"
EXTRA_OECMAKE += "-DSYSROOT_INCDIR=${STAGING_INCDIR}"
EXTRA_OECMAKE += "-DSYSROOT_LIBDIR=${STAGING_LIBDIR}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_INSTALL_BINDIR=${INSTALL_BINDIR}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_INSTALL_LIBDIR=${INSTALL_LIBDIR}"

EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_LICENSE=BSD"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_VERSION=${PV}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_PACKAGE=${PN}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_SUMMARY="${SUMMARY}""
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_ORIGIN=${HOMEPAGE}"

EXTRA_OECMAKE += "-DGST_IMAGE_MAX_WIDTH=${IMAGE_MAX_WIDTH}"
EXTRA_OECMAKE += "-DGST_IMAGE_MAX_HEIGHT=${IMAGE_MAX_HEIGHT}"

EXTRA_OECMAKE += "-DGST_VIDEO_MAX_WIDTH=${VIDEO_MAX_WIDTH}"
EXTRA_OECMAKE += "-DGST_VIDEO_MAX_HEIGHT=${VIDEO_MAX_HEIGHT}"
EXTRA_OECMAKE += "-DGST_VIDEO_MAX_FPS=${VIDEO_MAX_FPS}"
EXTRA_OECMAKE += "-DGST_VIDEO_H265_ENABLE=${VIDEO_H265_ENABLE}"
EXTRA_OECMAKE += "-DCAMERA_METADATA_VERSION=${CAMERA_METADATA_VERSION}"
EXTRA_OECMAKE += "-DGST_VIDEO_YUY2_FORMAT_ENABLE=${VIDEO_YUY2_FORMAT_ENABLE}"
EXTRA_OECMAKE += "-DGST_VIDEO_UYVY_FORMAT_ENABLE=${VIDEO_UYVY_FORMAT_ENABLE}"
EXTRA_OECMAKE += "-DGST_VIDEO_P010_10LE_FORMAT_ENABLE=${VIDEO_P010_10LE_FORMAT_ENABLE}"
EXTRA_OECMAKE += "-DGST_VIDEO_NV12_10LE32_FORMAT_ENABLE=${VIDEO_NV12_10LE32_FORMAT_ENABLE}"
EXTRA_OECMAKE += "-DGST_IMAGE_NV12_FORMAT_ENABLE=${IMAGE_NV12_FORMAT_ENABLE}"
EXTRA_OECMAKE += "-DMULTI_CAMERA_ENABLE=${MULTI_CAMERA_ENABLE}"

FILES:${PN} += "${INSTALL_BINDIR}"
FILES:${PN} += "${INSTALL_LIBDIR}"

SOLIBS = ".so*"
FILES_SOLIBSDEV = ""
