inherit cmake

SUMMARY = "QTI open-source GStreamer Plug-in for qmmf-sdk"
HOMEPAGE = "http://www.qualcomm.com"
SECTION = "multimedia"

LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/${LICENSE};md5=3775480a712fc46a69647678acb234cb"

# Dependencies.
DEPENDS := "gstreamer1.0"
DEPENDS += "gstreamer1.0-plugins-base"
DEPENDS += "qmmf-sdk"

FILESPATH =+ "${WORKSPACE}/vendor/qcom/opensource/gst-plugins-qti-oss/:"
SRC_URI = "file://gst-plugin-qmmfsrc/"
S = "${WORKDIR}/gst-plugin-qmmfsrc/"

# Install directries.
INSTALL_BINDIR := "${bindir}"
INSTALL_LIBDIR := "${libdir}"

# Default platform definitions.
VIDEO_MAX_WIDTH         := "4096"
VIDEO_MAX_HEIGHT        := "4096"
VIDEO_MAX_FPS           := "120/1"
VIDEO_H265_ENABLE       := "TRUE"
CAMERA_METADATA_VERSION := "1.0"

# Overwrite the default platform definitions for 8009.
VIDEO_MAX_WIDTH_apq8009   := "1920"
VIDEO_MAX_HEIGHT_apq8009  := "1080"
VIDEO_MAX_FPS_apq8009     := "30/1"
VIDEO_H265_ENABLE_apq8009 := "FALSE"

# Overwrite the default platform definitions for qrb5165.
VIDEO_MAX_FPS_qrb5165           := "240/1"
CAMERA_METADATA_VERSION_qrb5165 := "1.1"

EXTRA_OECMAKE += "-DGST_VERSION_REQUIRED=1.14.4"
EXTRA_OECMAKE += "-DSYSROOT_INCDIR=${STAGING_INCDIR}"
EXTRA_OECMAKE += "-DSYSROOT_LIBDIR=${STAGING_LIBDIR}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_INSTALL_BINDIR=${INSTALL_BINDIR}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_INSTALL_LIBDIR=${INSTALL_LIBDIR}"

EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_LICENSE=${LICENSE}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_VERSION=${PV}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_PACKAGE=${PN}"
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_SUMMARY="${SUMMARY}""
EXTRA_OECMAKE += "-DGST_PLUGINS_QTI_OSS_ORIGIN=${HOMEPAGE}"

EXTRA_OECMAKE += "-DGST_VIDEO_MAX_WIDTH=${VIDEO_MAX_WIDTH}"
EXTRA_OECMAKE += "-DGST_VIDEO_MAX_HEIGHT=${VIDEO_MAX_HEIGHT}"
EXTRA_OECMAKE += "-DGST_VIDEO_MAX_FPS=${VIDEO_MAX_FPS}"
EXTRA_OECMAKE += "-DGST_VIDEO_H265_ENABLE=${VIDEO_H265_ENABLE}"
EXTRA_OECMAKE += "-DCAMERA_METADATA_VERSION=${CAMERA_METADATA_VERSION}"

FILES_${PN} += "${INSTALL_BINDIR}"
FILES_${PN} += "${INSTALL_LIBDIR}"

SOLIBS = ".so*"
FILES_SOLIBSDEV = ""
